version: '3.1'

services:
#  zookeeper:
#    image: wurstmeister/zookeeper
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: wurstmeister/kafka
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
##      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,CONNECTIONS_FROM_HOST://localhost:19092
##      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
##      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://localhost:19092
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CREATE_TOPICS: "account-events:1:1"

  eureka-server:
    build: ./eureka-service
    container_name: eureka-service
    hostname: eureka-service
    ports:
      - "8761:8761"

  currency-service:
    build: ./rate_currency_service-master
    container_name: currency-rate-service-1
    hostname: currency-rate-service-1
    ports:
      - "8084:8084"
    environment:
      EUREKA_HOST: "172.17.0.1"





