server:
  port: 8084

spring:
  application:
    name: currency-rate-service

cloud:
  eureka-host: localhost

currency:
  client:
    url: "https://cbr.ru/scripts/XML_daily.asp"
eureka:
  client:
    service-url:
      defaultZone: http://${cloud.eureka-host}:8761/eureka
    enabled: false



