server:
  port: 8084

spring:
  application:
    name: currency-rate-service


currency:
  client:
    url: "https://cbr.ru/scripts/XML_daily.asp"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false



