server:
  port: 8084

# Имя сервиса
spring:
  application:
    name: currency-rate-service


currency:
  client:
    url: "https://cbr.ru/scripts/XML_daily.asp"

#настройка подключения клиента к серверу Еврики c указанием url
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false



