
# Конфигурация Spring cloud gateway


# Общий Порт gateway
server:
  port: 8080

# Адреса сервисов
cloud:
  eureka-host: localhost
  processing-service-url: http://localhost:8090
  currency-service-url: http://localhost:8084
  identity-service-url: http://localhost:9797
  account-history-service-url: http://localhost:8015


# Имя сервиса Spring cloud gateway
spring:
  application:
    name: api-gateway-service

# Роутинг сервисов
  cloud:
    gateway:
      discovery:
        locator:
            enabled: true
            lower-case-service-id: true
      routes:
        - id: currency-rate-service
          uri: ${cloud.currency-service-url}
          predicates:
            - Path=/money/**
          filters:
            - AuthenticationFilter

        - id: exchange-processing-service
          uri: ${cloud.processing-service-url}
          predicates:
            - Path=/processing/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: ${cloud.identity-service-url}
          predicates:
            - Path=/auth/**

        - id: account-history-service
          uri: ${cloud.account-history-service-url}
          predicates:
            - Path=/history/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${cloud.eureka-host}:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
# Видимость логов при обращении к сервисам
logging:
  level:
    org.springframework.cloud.gateway: DEBUG