server:
  port: 8090

# Имя сервиса
spring:
  application:
    name: exchange-processing-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5433/processing
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db
    url: jdbc:postgresql://localhost:5433/processing
    user: postgres
    password: password

service:
  currency:
    url: http://localhost:8084

    #настройка подключения клиента к серверу Еврики c указанием url
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    enabled: false


