server:
  port: 8090

cloud:
  db-host: localhost
  eureka-host: localhost
  kafka-host: localhost
#  currency-url: http://localhost:8084

spring:
  application:
    name: exchange-processing-service
#Настроили порт кафки
  kafka:
    producer:
      bootstrap-servers: ${cloud.kafka-host}:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      request:
        timeout:
          ms: 1000
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://${cloud.db-host}:5433/processing
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db
    url: jdbc:postgresql://${cloud.db-host}:5433/processing
    user: postgres
    password: password

#service:
#  currency:
#    url: ${cloud.currency-url}
#eureka:
#  client:
#    service-url:
#      default-zone: http://${cloud.eureka-host}:8761/eureka/
#    enabled: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${cloud.eureka-host}:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
